# Generated by Django 3.2.23 on 2025-03-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='学号'),
        ),
    ]
