# Generated by Django 3.2.25 on 2025-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20250319_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_subjects',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_users', to='board.Subject'),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
