# Generated by Django 3.2.25 on 2025-03-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20250324_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopic',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='是否匿名'),
        ),
    ]
