# Generated by Django 3.2.25 on 2025-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_devicelogin_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelogin',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP地址'),
        ),
    ]
