# Generated by Django 3.2.25 on 2025-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_rating_ratingcomment_ratingcommentlike_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名发布'),
        ),
    ]
