# Generated by Django 3.2.25 on 2025-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_rating_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活动时间'),
        ),
    ]
